### ISSUE TITLE
默认终端变为这样

### ISSUE THREAD

**Issue by shang1219178163** [sirius1024/iterm2-with-oh-my-zsh#1]
![20190103183532](https://user-images.githubusercontent.com/3699729/50633497-75543d00-0f86-11e9-9427-8cab69e78fbd.png)

**Comment by sirius1024** [comment]
是会有这样的问题。老的bash您还用吗？我完全用iTerm2替代了。

**Comment by sirius1024** [comment]
如果还想兼容自带的bash，可以只安装oh my zsh，安装辅助插件，后面的样式不作调整。
![image](https://user-images.githubusercontent.com/6395714/50669239-fcdd9280-0ffe-11e9-8132-7b2249a2871b.png)

**Comment by shang1219178163** [comment]
👌

**Comment by CatSayInk** [comment]
是因为你没有安装Powerline Font并且切换到那几种字体
