### ISSUE TITLE
关于远程登陆linux服务器的问题

### ISSUE THREAD

**Issue by ichz** [sirius1024/iterm2-with-oh-my-zsh#2]
您好，根据你的教程配置都没有问题。但ssh登陆到服务器后，配色和显示就都没有了。还是根服务器的显示一样。请问有什么办法吗？毕竟我本机上使用的不多。主要都是登陆服务器。

**Comment by sirius1024** [comment]
https://github.com/hectorleiva/iterm2-ssh-color-scheme
FYI.
