### ISSUE TITLE
为什么需要安装PowerLine？

### ISSUE THREAD

**Issue by leeyesong** [sirius1024/iterm2-with-oh-my-zsh#4]
文章整理的很细致，一步步走下来配出了想要的效果。但我有一事不明，为什么需要安装PowerLine呢？文章最终用到的PowerLine字体、配色方案、agnoster主题好像都跟PowerLine没关系呢

**Comment by sirius1024** [comment]
Hi,
Powerline是agnoster主题的依赖。具体可以在repo里查询到：
https://github.com/agnoster/agnoster-zsh-theme

> NOTE: In all likelihood, you will need to install a Powerline-patched font for this theme to render correctly.

我会把这些信息补充到文章中，感谢指出。
